# Generated by Django 2.2.6 on 2019-10-29 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, null=True)),
                ('option1', models.CharField(max_length=30, null=True)),
                ('option2', models.CharField(max_length=30, null=True)),
                ('option3', models.CharField(max_length=30, null=True)),
                ('option4', models.CharField(max_length=30, null=True)),
                ('answer', models.CharField(max_length=30, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.Course')),
            ],
        ),
    ]
