# Generated by Django 2.2.6 on 2019-10-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='cat',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
