# Generated by Django 2.2.6 on 2019-10-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_userdetail_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='email',
        ),
    ]
