# Generated by Django 2.2.6 on 2019-10-30 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_auto_20191030_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='course',
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.Course'),
        ),
    ]
