# Generated by Django 2.2.6 on 2019-11-01 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_auto_20191101_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.UserDetail'),
        ),
    ]
