# Generated by Django 2.2.6 on 2019-11-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0011_auto_20191101_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizresult',
            old_name='user',
            new_name='bhu',
        ),
    ]
