# Generated by Django 2.2.6 on 2019-11-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0013_auto_20191102_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='course',
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
