# Generated by Django 2.2.6 on 2019-11-03 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0015_remove_quizresult_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='question',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.Topic'),
        ),
    ]
