# Generated by Django 2.2.6 on 2019-11-03 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0017_auto_20191103_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='final',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.FinalResult'),
        ),
    ]
