# Generated by Django 2.2.6 on 2019-11-03 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0018_quizresult_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalresult',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.Topic'),
        ),
    ]
