# Generated by Django 2.2.6 on 2019-11-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0019_finalresult_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='final',
        ),
    ]
