# Generated by Django 2.2.6 on 2019-11-03 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0020_remove_quizresult_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalresult',
            name='topic',
        ),
        migrations.AddField(
            model_name='finalresult',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.QuizResult'),
        ),
    ]
